framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@test:
    framework:
        mailer:
            dsn: 'null://null'

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['martin@duss-janser.ch']
