language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - APP_ENV: test
    - APP_SECRET: l5XUAAp5ZXBC57ZnSWo2XnNLR1mcEm
    - MAILER_URL: "null://localhost"

before_script:
  - composer install --no-interaction --no-progress --no-suggest

script:
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --diff
  - ./vendor/bin/phpstan analyze --level 7 src/
  - ./bin/console security:check
