language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - secure: "dA+XBc38aTPk6ZNqG+NOTXPvEh14WkztNJXYku6qOn3zxUauobe3QRe6GXu9\nHKTTFdMqvW5RWYvkdaoKTKQSCyDxte2Kwpc9KFtRGrYkBS1B0VODSQI80ycP\nb/P6Gegf8GHnn3BHJG5QfmFR+iwgmEGMz1dh+gSTPpsGh9TaVrQ="

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --dev --prefer-source --no-scripts
  - php app/console doctrine:database:create --env test --no-interaction
  - php app/console doctrine:phpcr:init:dbal --env test --no-interaction
  - php app/console doctrine:phpcr:register-system-node-types --env test --no-interaction
  - php app/console doctrine:phpcr:workspace:create standard_test --env test --no-interaction
  - php app/console doctrine:phpcr:fixtures:load --env test --no-interaction
  - php app/console assets:install --symlink --no-interaction web
  - php app/console cache:clear --no-interaction
  - php app/console cache:clear --env test --no-interaction

script: ./vendor/bin/phpunit -c app --coverage-html build/coverage-report --coverage-text=build/coverage.txt

after_script:
  - ./vendor/bin/woodhouse publish mjanser/sg-tuggen-website build/coverage-report:coverage-report --message "Publishing coverage reports from build ${TRAVIS_BUILD_NUMBER} (php $(php -r 'echo phpversion();'))." --coverage-image coverage-report/coverage.png --coverage-phpunit build/coverage.txt --no-interaction --auth-token-env GITHUB_TOKEN
