imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "SgTuggenMainBundle:Form:fields.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [SymfonyCmfSimpleCmsBundle, SymfonyCmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #lessphp:
            #file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            #apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

swiftmailer:
    transport:  %mailer_transport%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    #spool:      { type: memory }
    disable_delivery: %mailer_disable_delivery%
    delivery_address: %mailer_delivery_address%

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

symfony_cmf_routing_extra:
    dynamic:
        enabled: true

symfony_cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:  SymfonyCmfSimpleCmsBundle:Page:index.html.twig
    use_sonata_admin: false

knp_menu:
    twig: true

symfony_cmf_menu:
    use_sonata_admin: false
    menu_basepath: /cms

#symfony_cmf_create:
#    phpcr_odm: true
