services:
    symfony_cmf_menu.provider:
        class: SgTuggen\MainBundle\Menu\MenuProvider
        arguments:
          - @service_container
          - @symfony_cmf_menu.factory
          - %symfony_cmf_menu.document_manager_name%
          - %symfony_cmf_menu.menu_basepath%
        tags:
          - { name: knp_menu.provider, alias: simple }