parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Application\:
    #     resource: '../src/Application'

    # Domain\:
    #     resource: '../src/Domain'
            
    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastrucutre/Symfony/DependencyInjection/'
            - '../src/Infrastructure/Symfony/Kernel.php'
